create table Worker(id_worker int PRIMARY KEY IDENTITY,surname_worker varchar(30),name_worker varchar(30),thrid_name_worker varchar(30),post_worker varchar(30))
create table Project(id_project int PRIMARY KEY IDENTITY,name_project varchar(100),abbreviate_project varchar(50),information varchar(200))
create table Task(id_task int PRIMARY KEY IDENTITY,name_task varchar(100),time_task int,date_start datetime,date_finish datetime,status_task varchar(50),id_project int,FOREIGN KEY (id_project) REFERENCES Project(id_project) ON DELETE CASCADE)
create table TaskList(id_taskList int PRIMARY KEY IDENTITY,id_task int,id_worker int,FOREIGN KEY (id_task) REFERENCES Task(id_task) ON DELETE CASCADE,FOREIGN KEY (id_worker) REFERENCES Worker(id_worker) ON DELETE CASCADE)
insert into Project values(default, 'Project1', 'P1', 'Information about project1')
insert into Project values(default, 'Project2', 'P2', 'Information about project2')
insert into Project values(default, 'Project3', 'P3', 'Information about project3')
insert into Project values(default, 'Project4', 'P4', 'Information about project4')
insert into Task values(default, 'Task1', 8, '2016-07-21', '2016-07-21' , 'in progress', 1)
insert into Task values(default, 'Task2', 4, '2016-07-21', '2016-07-21' , 'in progress', 1)
insert into Task values(default, 'Task3', 2, '2016-07-21', '2016-07-21' , 'unbegun', 1)
insert into Task values(default, 'Task4', 8, '2016-07-21', '2016-07-21' , 'finish', 2)
insert into Worker values(default, 'Surname1', 'Name1', 'ThridName1' , 'post1')
insert into Worker values(default, 'Surname2', 'Name2', 'ThridName2' , 'post1')
insert into Worker values(default, 'Surname3', 'Name3', 'ThridName3' , 'post2')
insert into Worker values(default, 'Surname4', 'Name4', 'ThridName4' , 'post2')
insert into Worker values(default, 'Surname5', 'Name5', 'ThridName5' , 'post3')
insert into Worker values(default, 'Surname6', 'Name6', 'ThridName6' , 'post4')
insert into TaskList values(default, 0, 0)
insert into TaskList values(default, 1, 1)
insert into TaskList values(default, 2, 2)
insert into TaskList values(default, 3, 3)